const E=window.LiquidityEngine;
const scenarios={
  safe:{id:'safe',name:'NOVA Exchange — Safe Treasury',operatingLiquidity:3_000_000,outflowRatePerMinute:100_000,bottleneck:'None',routes:[{id:'sol',name:'Solana Reserve',amount:1_000_000,etaSeconds:4,state:'AVAILABLE',provenance:'SCENARIO'},{id:'cex',name:'CEX Reserve Settlement',amount:2_000_000,etaSeconds:12*60,state:'SCHEDULED',provenance:'CONFIGURED'},{id:'token',name:'Tokenized Reserve',amount:4_000_000,etaSeconds:30*60,state:'STANDBY',provenance:'CONFIGURED'},{id:'bank',name:'Bank Facility',amount:5_000_000,etaSeconds:45*60,state:'STANDBY',provenance:'CONFIGURED'}]},
  stress:{id:'stress',name:'NOVA Exchange — Timing Stress',operatingLiquidity:1_500_000,outflowRatePerMinute:150_000,bottleneck:'Settlement latency',routes:[{id:'sol',name:'Solana Reserve',amount:3_150_000,etaSeconds:4,state:'AVAILABLE',provenance:'SCENARIO'},{id:'cex',name:'CEX Reserve Settlement',amount:2_000_000,etaSeconds:17*60,state:'SCHEDULED',provenance:'CONFIGURED'},{id:'token',name:'Tokenized Reserve',amount:4_000_000,etaSeconds:30*60,state:'STANDBY',provenance:'CONFIGURED'},{id:'bank',name:'Bank Facility',amount:5_000_000,etaSeconds:45*60,state:'STANDBY',provenance:'CONFIGURED'}]},
  rescue:{id:'rescue',name:'NOVA Exchange — On-chain Rescue',operatingLiquidity:1_500_000,outflowRatePerMinute:150_000,bottleneck:'Settlement latency',autoRescue:true,routes:[{id:'sol',name:'Solana Reserve',amount:3_150_000,etaSeconds:4,state:'AVAILABLE',provenance:'SCENARIO'},{id:'cex',name:'CEX Reserve Settlement',amount:2_000_000,etaSeconds:17*60,state:'SCHEDULED',provenance:'CONFIGURED'},{id:'token',name:'Tokenized Reserve',amount:4_000_000,etaSeconds:30*60,state:'STANDBY',provenance:'CONFIGURED'},{id:'bank',name:'Bank Facility',amount:5_000_000,etaSeconds:45*60,state:'STANDBY',provenance:'CONFIGURED'}]}
};
let currentKey='stress';let executedAmount=0;let executedRouteId=null;let executing=false;
const $=id=>document.getElementById(id);
function provenancePill(p){return `<span class="pill ${p==='ON_CHAIN'?'onchain':p==='CONFIGURED'?'configured':'scenario'}">${p.replace('_',' ')}</span>`}
function stateAssessment(route,scenario){
  if(route.state==='EXECUTABLE') return ['Executable now','s-good'];
  if(route.state==='AVAILABLE'){const post=E.firstBindingGap(scenario,scenario.operatingLiquidity+executedAmount+route.amount);return [post.gapSeconds>=0?'Sufficient if deployed':'Partial only',post.gapSeconds>=0?'s-good':'s-warn'];}
  if(route.state==='SCHEDULED') return ['Committed route','s-warn'];
  if(route.state==='DEPLOYED') return ['Moved to operating wallet','s-good'];
  return ['Standby',''];
}
function render(){
  const s=structuredClone(scenarios[currentKey]);
  const liveOperating=s.operatingLiquidity+executedAmount;
  const engineRoutes=executedRouteId?s.routes.filter(r=>r.id!==executedRouteId):s.routes;
  const engineScenario={...s,operatingLiquidity:liveOperating,routes:engineRoutes};
  const analysis=E.analyze(engineScenario);const base=analysis.base;const next=base.route;
  $('scenarioName').textContent=s.name;$('bufferClock').textContent=E.fmtSeconds(analysis.bufferSeconds);$('nextClock').textContent=next?E.fmtSeconds(next.etaSeconds):'—';$('nextRouteName').textContent=next?next.name:'No committed route';
  const gap=base.gapSeconds;$('survivalGap').textContent=E.fmtSeconds(gap);$('survivalGap').className='gap '+(gap>=0?'positive':'negative');$('gapCard').className='gap-card '+(gap>=0?'positive-card':'');$('gapStatus').textContent=gap>=0?'CURRENT PLAN SURVIVES':'LIQUIDITY ARRIVES TOO LATE';$('gapExplain').textContent=gap>=0?'Current executable liquidity survives until the next committed source becomes available.':'Current liquidity is exhausted before the next committed source becomes executable.';
  $('metricExecutable').textContent=E.fmtM(liveOperating);$('metricOutflow').textContent=E.fmtM(s.outflowRatePerMinute);$('metricNominal').textContent=E.fmtM(s.operatingLiquidity+s.routes.reduce((a,r)=>a+r.amount,0));$('metricBottleneck').textContent=gap>=0?'No binding timing gap':s.bottleneck;$('metricBottleneckNote').textContent=gap>=0?'within current horizon':'first gap';
  const displayRoutes=s.routes.map(r=>r.id===executedRouteId?{...r,amount:0,state:'DEPLOYED',provenance:'ON_CHAIN'}:r);const rows=[{name:'Operating Wallet',amount:liveOperating,etaSeconds:0,state:'EXECUTABLE',provenance:'SCENARIO'},...displayRoutes];
  $('routesBody').innerHTML=rows.map(r=>{const [assess,cls]=stateAssessment(r,{...s,operatingLiquidity:liveOperating});const timing=r.state==='EXECUTABLE'?'Now':r.state==='AVAILABLE'?`~${r.etaSeconds}s if executed`:r.state==='DEPLOYED'?'Confirmed on-chain':E.fmtSeconds(r.etaSeconds);return `<tr><td><strong>${r.name}</strong></td><td>${E.fmtM(r.amount)} LQUSD</td><td><span class="state">${timing}</span><br><small>${r.state}</small></td><td>${provenancePill(r.provenance)}</td><td class="${cls}">${assess}</td></tr>`;}).join('');
  const rec=analysis.recommendation;if(gap>=0){$('actionTitle').textContent='No intervention required';$('actionAmount').textContent='Current plan remains viable';$('actionReason').textContent='The executable buffer reaches the next committed liquidity source before exhaustion.';$('actionEffect').textContent=`${E.fmtSeconds(gap)} gap`;$('executeBtn').disabled=true;}else if(rec){$('actionTitle').textContent=`Deploy ${rec.name}`;$('actionAmount').textContent=`${E.fmtM(rec.amount)} LQUSD`;$('actionReason').textContent=rec.sufficient?'Fastest available source large enough to bridge the first binding timing gap.':'No available route fully closes the gap; this is the fastest partial intervention.';$('actionEffect').textContent=`${E.fmtSeconds(gap)} → ${E.fmtSeconds(rec.effectSeconds)}`;$('executeBtn').disabled=executing||executedAmount>0;}
  const initial=E.analyze(s);$('beforeExecutable').textContent=E.fmtM(s.operatingLiquidity);$('afterExecutable').textContent=E.fmtM(liveOperating);$('beforeBuffer').textContent=E.fmtSeconds(initial.bufferSeconds);$('afterBuffer').textContent=E.fmtSeconds(analysis.bufferSeconds);$('beforeGap').textContent=E.fmtSeconds(initial.base.gapSeconds);$('afterGap').textContent=E.fmtSeconds(gap);$('afterGap').className=gap>=0?'positive-text':'negative-text';document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===currentKey));
}
async function execute(){
  const s=scenarios[currentKey];const analysis=E.analyze({...s,operatingLiquidity:s.operatingLiquidity+executedAmount});const rec=analysis.recommendation;if(!rec||executing||executedAmount>0)return;
  executing=true;$('executeBtn').disabled=true;$('executeBtn').textContent='CONFIRMING…';$('proofStatus').textContent='Executing liquidity route';$('proofTxStatus').textContent='CONFIRMING';$('proofAmount').textContent=`${E.fmtM(rec.amount)} LQUSD`;
  try{const proof=await window.SolanaAdapter.execute({amount:rec.amount,route:rec});if(!proof.ok)throw new Error('Execution failed');executedAmount+=rec.amount;executedRouteId=rec.id;$('proofStatus').textContent='Confirmed on Solana';$('proofAmount').textContent=`${proof.proofTransferSol.toFixed(5)} SOL proof / ${E.fmtM(rec.amount)} LQUSD scenario`;$('proofTxStatus').textContent=String(proof.confirmationStatus||'CONFIRMED').toUpperCase();$('proofNetwork').textContent=proof.network||'SOLANA DEVNET';$('proofExecution').textContent=`${proof.executionSeconds.toFixed(2)} sec`;$('proofNetworkTime').textContent=proof.networkSeconds!=null?`${proof.networkSeconds.toFixed(2)} sec`:'—';$('proofSignature').textContent=proof.signature;$('proofSlot').textContent=proof.slot??'—';if(proof.explorer){$('proofExplorer').href=proof.explorer;$('proofExplorer').hidden=false;}$('proofNote').textContent=proof.note||'Verified Solana Devnet settlement. Balance is recalculated from the confirmed state.';updateWalletState();}
  catch(err){$('proofStatus').textContent='Transaction failed';$('proofTxStatus').textContent='FAILED';$('proofNote').textContent=String(err);}
  executing=false;$('executeBtn').textContent='EXECUTE LIQUIDITY';render();
}
function reset(){executedAmount=0;executedRouteId=null;executing=false;$('proofStatus').textContent='Awaiting intervention';$('proofTxStatus').textContent='NOT SUBMITTED';$('proofAmount').textContent='—';$('proofExecution').textContent='—';$('proofNetworkTime').textContent='—';$('proofSignature').textContent='—';$('proofSlot').textContent='—';$('proofExplorer').hidden=true;$('proofExplorer').href='#';$('proofNetwork').textContent='SOLANA DEVNET';$('proofNote').textContent='Connect a development Phantom wallet. The final execution state is applied only after a real Solana Devnet transaction confirms.';render();if(scenarios[currentKey].autoRescue)setTimeout(execute,450)}
function shortAddr(a){return !a?'Not connected':a.length>18?`${a.slice(0,7)}…${a.slice(-7)}`:a}
async function updateWalletState(){try{const st=await window.SolanaAdapter.getState();$('walletAddress').textContent=st.connected?shortAddr(st.wallet):(st.available?'Phantom available — not connected':'Phantom not detected');$('walletAddress').title=st.wallet||'';$('walletBalance').textContent=st.connected?`${st.balanceSol.toFixed(5)} SOL`:'—';$('connectWalletBtn').textContent=st.connected?'WALLET CONNECTED':'CONNECT PHANTOM';$('fundWalletBtn').disabled=!st.connected;}catch(e){$('walletAddress').textContent='Wallet status unavailable';$('walletBalance').textContent='—';}}
async function connectWallet(){$('connectWalletBtn').disabled=true;$('connectWalletBtn').textContent='CONNECTING…';try{await window.SolanaAdapter.connect();await updateWalletState();}catch(e){$('proofStatus').textContent='Wallet connection required';$('proofNote').textContent=String(e);}$('connectWalletBtn').disabled=false;}
async function fundWallet(){$('fundWalletBtn').disabled=true;$('fundWalletBtn').textContent='FUNDING…';try{const r=await window.SolanaAdapter.fundDevnet(0.02);$('proofStatus').textContent=r.alreadyFunded?'Devnet wallet already funded':'Devnet funding confirmed';$('proofNote').textContent=r.alreadyFunded?'No faucet transaction was needed.':'Test SOL received on Solana Devnet. Ready for the execution proof.';await updateWalletState();}catch(e){$('proofStatus').textContent='Devnet funding failed';$('proofNote').textContent=String(e);}$('fundWalletBtn').textContent='FUND DEVNET';$('fundWalletBtn').disabled=false;}
document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{currentKey=btn.dataset.scenario;reset()}));$('executeBtn').addEventListener('click',execute);$('resetBtn').addEventListener('click',reset);$('connectWalletBtn').addEventListener('click',connectWallet);$('fundWalletBtn').addEventListener('click',fundWallet);reset();updateWalletState();
