const E=window.LiquidityEngine;
const scenarios={
  safe:{id:'safe',name:'NOVA Exchange — Safe Treasury',operatingLiquidity:3_000_000,outflowRatePerMinute:100_000,routes:[{id:'sol',name:'Solana Reserve',amount:1_000_000,etaSeconds:4,state:'AVAILABLE'},{id:'cex',name:'CEX Reserve',amount:2_000_000,etaSeconds:720,state:'SCHEDULED'},{id:'token',name:'Tokenized Reserve',amount:4_000_000,etaSeconds:1800,state:'STANDBY'},{id:'bank',name:'Bank Facility',amount:5_000_000,etaSeconds:2700,state:'STANDBY'}]},
  stress:{id:'stress',name:'NOVA Exchange — Timing Stress',operatingLiquidity:1_500_000,outflowRatePerMinute:150_000,routes:[{id:'sol',name:'Solana Reserve',amount:3_150_000,etaSeconds:5,state:'AVAILABLE'},{id:'cex',name:'CEX Reserve',amount:2_000_000,etaSeconds:1020,state:'SCHEDULED'},{id:'token',name:'Tokenized Reserve',amount:4_000_000,etaSeconds:1800,state:'STANDBY'},{id:'bank',name:'Bank Facility',amount:5_000_000,etaSeconds:2700,state:'STANDBY'}]},
  rescue:{id:'rescue',name:'NOVA Exchange — On-chain Rescue Preview',operatingLiquidity:1_500_000,outflowRatePerMinute:150_000,previewRescue:true,routes:[{id:'sol',name:'Solana Reserve',amount:3_150_000,etaSeconds:5,state:'AVAILABLE'},{id:'cex',name:'CEX Reserve',amount:2_000_000,etaSeconds:1020,state:'SCHEDULED'}]},
  custom:{id:'custom',name:'Custom Treasury — User-defined Stress',operatingLiquidity:1_500_000,outflowRatePerMinute:150_000,routes:[{id:'sol',name:'Solana Reserve',amount:3_150_000,etaSeconds:5,state:'AVAILABLE'},{id:'cex',name:'Next Committed Route',amount:2_000_000,etaSeconds:1020,state:'SCHEDULED'}]}
};
let currentKey='stress',executedAmount=0,executedRouteId=null,executing=false,lastValues={buffer:null,next:null,gap:null},lastSignature='';
const $=id=>document.getElementById(id);
const fmtAmount=a=>`${E.fmtM(a)} LQUSD`;
const fmtGap=s=>!Number.isFinite(s)?'—':`${s>0?'+':''}${E.fmtSeconds(s)}`;
const shortAddr=a=>!a?'Creating demo wallet…':a.length>18?`${a.slice(0,7)}…${a.slice(-7)}`:a;
const cssStatus=s=>`status-${s.toLowerCase()}`;
const iconFor=id=>id==='sol'?'S':id==='cex'?'↗':id==='token'?'◫':id==='bank'?'▥':'●';
function notice(message,tone='info'){const el=$('interactionNotice');el.textContent=message;el.dataset.tone=tone;el.hidden=!message}
function setActionHint(text){$('actionHint').textContent=text}
function setNetworkState(state,label){$('networkStatusText').textContent=label;$('networkStatusDot').className=`status-dot ${state}`;$('chainPill').dataset.network=state}
function animateText(el,from,to,formatter,duration=450){if(from===null||!Number.isFinite(from)||!Number.isFinite(to)){el.textContent=formatter(to);return}const start=performance.now();function step(t){const p=Math.min(1,(t-start)/duration),eased=1-Math.pow(1-p,3);el.textContent=formatter(from+(to-from)*eased);if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function bump(el){el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump');setTimeout(()=>el.classList.remove('bump'),380)}
function dialAngle(seconds,maxSeconds=1800){return Math.max(48,Math.min(278,(seconds/maxSeconds)*278))}
function updateDial(id,seconds){$(id).style.setProperty('--angle',`${dialAngle(seconds)}deg`)}
function buildLiveScenario(){const raw=structuredClone(scenarios[currentKey]);const liveOperating=raw.operatingLiquidity+executedAmount;const engineRoutes=executedRouteId?raw.routes.filter(r=>r.id!==executedRouteId):raw.routes;return{raw,liveOperating,engineScenario:{...raw,operatingLiquidity:liveOperating,routes:engineRoutes}}}
function renderRoutes(s,liveOperating){const displayRoutes=s.routes.map(r=>r.id===executedRouteId?{...r,amount:0,state:'DEPLOYED'}:r);const rows=[{id:'operating',name:'Operating Wallet',amount:liveOperating,etaSeconds:0,state:'EXECUTABLE'},...displayRoutes];$('routesBody').innerHTML=rows.map(r=>{const arrival=r.state==='EXECUTABLE'?'Now':r.state==='AVAILABLE'?`~ ${r.etaSeconds} sec`:r.state==='DEPLOYED'?'Confirmed':`${Math.round(r.etaSeconds/60)} min`;const rowClass=r.id==='sol'&&!executedRouteId?'route-highlight route-pulse':r.state==='DEPLOYED'?'route-confirmed':'';return `<tr class="${rowClass}"><td><div class="source-cell"><span class="source-icon">${iconFor(r.id)}</span>${r.name}</div></td><td>${fmtAmount(r.amount)}</td><td>${arrival}</td><td><span class="status-pill ${cssStatus(r.state)}">${r.state[0]+r.state.slice(1).toLowerCase()}</span></td></tr>`}).join('')}
function render(animate=true){
  const {raw:s,liveOperating,engineScenario}=buildLiveScenario();
  const analysis=E.analyze(engineScenario),base=analysis.base,next=base.route,gap=base.gapSeconds,initial=E.analyze(s),rec=analysis.recommendation;
  $('scenarioName').textContent=s.name;$('customPanel').hidden=currentKey!=='custom';
  if(animate){animateText($('bufferClock'),lastValues.buffer,analysis.bufferSeconds,E.fmtSeconds);animateText($('nextClock'),lastValues.next,next?.etaSeconds??0,E.fmtSeconds);animateText($('survivalGap'),lastValues.gap,gap,fmtGap,550);bump($('survivalGap'))}
  else{$('bufferClock').textContent=E.fmtSeconds(analysis.bufferSeconds);$('nextClock').textContent=next?E.fmtSeconds(next.etaSeconds):'—';$('survivalGap').textContent=fmtGap(gap)}
  lastValues={buffer:analysis.bufferSeconds,next:next?.etaSeconds??0,gap};updateDial('bufferDial',analysis.bufferSeconds);updateDial('nextDial',next?.etaSeconds??0);
  $('survivalGap').className=`gap-value ${gap>=0?'positive':'negative'}`;$('gapCard').className=`gap-card card ${gap>=0?'positive-card':''}`;$('gapStatus').textContent=gap>=0?'Current plan survives.':'Liquidity arrives too late.';$('gapAlert').querySelector('span').textContent=gap>=0?'✓':'!';
  $('metricExecutable').textContent=fmtAmount(liveOperating);$('nextRouteName').textContent=next?next.name:'No committed route';$('nextAmount').textContent=next?fmtAmount(next.amount):'—';renderRoutes(s,liveOperating);
  if(gap>=0){$('actionTitle').textContent='No intervention required';$('actionAmount').textContent='Current plan survives';$('executeBtn').disabled=true;$('executeBtn').querySelector('span').textContent='No Execution Required';$('projectedGap').textContent=fmtGap(gap);$('projectedGap').className='positive-text';setActionHint('This scenario already survives. Choose Timing Stress, On-chain Rescue, or Custom Stress to test execution.')}
  else if(rec){$('actionTitle').textContent=`Deploy ${rec.name}`;$('actionAmount').textContent=fmtAmount(rec.amount);$('executeBtn').disabled=executing||executedAmount>0;$('executeBtn').querySelector('span').textContent=executedAmount>0?'Proof Executed':executing?'Running Live Proof…':'Run Live Devnet Proof';$('projectedGap').textContent=fmtGap(rec.effectSeconds);$('projectedGap').className=rec.effectSeconds>=0?'positive-text':'negative-text';if(executedAmount>0)setActionHint('Execution proof confirmed. Use the Explorer link below for independent verification.');else setActionHint('One click creates a temporary in-memory Devnet wallet, funds it with test SOL, signs locally, and submits a real transaction. No Phantom required.')}
  else{$('actionTitle').textContent='No executable route available';$('actionAmount').textContent='Adjust the scenario inputs';$('executeBtn').disabled=true;$('executeBtn').querySelector('span').textContent='Execution Unavailable';$('projectedGap').textContent='—';$('projectedGap').className='negative-text';setActionHint('No AVAILABLE route can close this timing gap. Adjust the scenario or add an executable route.')}
  $('beforeGap').textContent=fmtGap(initial.base.gapSeconds);$('beforeExecutable').textContent=E.fmtM(s.operatingLiquidity);$('afterExecutable').textContent=E.fmtM(liveOperating);$('beforeBuffer').textContent=E.fmtSeconds(initial.bufferSeconds);$('afterBuffer').textContent=E.fmtSeconds(analysis.bufferSeconds);$('impactBeforeGap').textContent=fmtGap(initial.base.gapSeconds);$('afterGap').textContent=fmtGap(gap);$('afterGap').className=gap>=0?'positive-text':'negative-text';
  document.querySelectorAll('[data-scenario]').forEach(b=>{const active=b.dataset.scenario===currentKey;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.setAttribute('tabindex',active?'0':'-1')});
}
function setProgressByPhase(phase){const map={prepare:0,fund:0,sign:1,submit:2,confirm:3,complete:4};const stepIndex=map[phase]??0;const steps=[...document.querySelectorAll('.progress-step')];steps.forEach((el,i)=>{el.classList.toggle('done',i<stepIndex);el.classList.toggle('active',i===stepIndex)});$('progressFill').style.width=`${Math.max(0,Math.min(100,(stepIndex/(steps.length-1))*100))}%`}
function resetProgress(){setProgressByPhase('prepare')}
function setProofStatus(title,status='NOT SUBMITTED'){$('proofStatus').textContent=title;$('proofTxStatus').textContent=status}
async function checkNetwork(scroll=false){setNetworkState('checking','checking');if(scroll){$('executionPanel').scrollIntoView({behavior:'smooth',block:'center'});notice('Checking Solana Devnet RPC…','info')}try{const r=await window.SolanaAdapter.checkNetwork();if(r.ok){setNetworkState('online',`${r.latencyMs}ms`);$('chainPill').title=`Devnet RPC online • ${r.latencyMs} ms • click to refresh`;if(scroll)notice(`Solana Devnet RPC is reachable (${r.latencyMs} ms).`,'success')}else{setNetworkState('offline','offline');$('chainPill').title='Devnet RPC unavailable — click to retry';if(scroll)notice('Solana Devnet RPC is not reachable right now. Retry in a moment.','error')}}catch(e){setNetworkState('offline','offline');if(scroll)notice('Could not verify Solana Devnet RPC.','error')}}
async function updateDemoState(){try{const st=await window.SolanaAdapter.getState();$('walletAddress').textContent=`Ephemeral demo wallet ${shortAddr(st.wallet)}`;$('walletAddress').title=st.wallet||'';$('walletBalance').textContent=st.connected?`${st.balanceSol.toFixed(5)} SOL`:'—';return st}catch(e){$('walletAddress').textContent='Demo wallet unavailable';$('walletBalance').textContent='—';return{available:false,connected:false}}}
async function execute(){
  const {engineScenario}=buildLiveScenario();const analysis=E.analyze(engineScenario),rec=analysis.recommendation;
  if(!rec||executing||executedAmount>0)return;
  notice('');executing=true;$('executeBtn').disabled=true;$('executeBtn').querySelector('span').textContent='Running Live Proof…';
  try{
    const proof=await window.SolanaAdapter.execute({amount:rec.amount,route:rec,onPhase:phase=>{setProgressByPhase(phase);const text={prepare:['Preparing temporary Devnet wallet','PREPARING'],fund:['Funding temporary wallet with test SOL','FUNDING'],sign:['Signing locally in browser memory','SIGNED LOCALLY'],submit:['Submitting to Solana Devnet','SUBMITTED'],confirm:['Confirming on Solana','CONFIRMING'],complete:['Confirmed on Solana','CONFIRMED']}[phase];if(text)setProofStatus(text[0],text[1])}});
    if(!proof.ok)throw new Error('Execution failed');
    executedAmount+=rec.amount;executedRouteId=rec.id;lastSignature=proof.signature;
    $('proofExecution').textContent=`${proof.executionSeconds.toFixed(2)} sec`;$('proofSignature').textContent=proof.signature;$('proofSignature').title=proof.signature;$('proofSlot').textContent=proof.slot??'—';$('proofExplorer').href=proof.explorer;$('proofExplorer').hidden=false;$('copySignatureBtn').hidden=false;
    notice('Real Devnet proof confirmed. The signing key existed only in browser memory; the LQUSD financial scenario remains synthetic.','success');render(true);await updateDemoState();
  }catch(err){setProofStatus('Live Devnet proof not completed','FAILED');$('proofExecution').textContent='—';notice(err.message||'Transaction failed.','error');resetProgress();console.error(err)}
  finally{executing=false;render(false)}
}
function reset(){executedAmount=0;executedRouteId=null;executing=false;lastSignature='';lastValues={buffer:null,next:null,gap:null};setProofStatus('Ready — no wallet required','NOT SUBMITTED');$('proofExecution').textContent='—';$('proofSignature').textContent='—';$('proofSlot').textContent='—';$('proofExplorer').hidden=true;$('proofExplorer').href='#';$('copySignatureBtn').hidden=true;$('copySignatureBtn').textContent='Copy signature';$('faucetLink').hidden=true;notice('');resetProgress();render(true);updateDemoState()}
function applyCustomScenario(){const inputs=[...$('customPanel').querySelectorAll('input')];if(inputs.some(i=>!i.checkValidity())){inputs.find(i=>!i.checkValidity())?.reportValidity();notice('Check the custom scenario values before recalculating.','error');return}const operating=Number($('customOperating').value)*1e6,outflow=Number($('customOutflow').value)*1e3,nextAmount=Number($('customNextAmount').value)*1e6,nextEta=Number($('customNextEta').value)*60,reserve=Number($('customReserve').value)*1e6,reserveEta=Number($('customReserveEta').value);if([operating,outflow,nextAmount,nextEta,reserve,reserveEta].some(v=>!Number.isFinite(v)||v<=0)){notice('All custom values must be positive numbers.','error');return}scenarios.custom={id:'custom',name:'Custom Treasury — User-defined Stress',operatingLiquidity:operating,outflowRatePerMinute:outflow,routes:[{id:'sol',name:'Solana Reserve',amount:reserve,etaSeconds:reserveEta,state:'AVAILABLE'},{id:'cex',name:'Next Committed Route',amount:nextAmount,etaSeconds:nextEta,state:'SCHEDULED'}]};currentKey='custom';reset();notice('Custom scenario recalculated.','success')}
function toggleSyntheticInfo(){const panel=$('syntheticInfoPanel'),btn=$('syntheticInfoBtn'),open=panel.hidden;panel.hidden=!open;btn.setAttribute('aria-expanded',String(open))}
async function copySignature(){if(!lastSignature)return;try{await navigator.clipboard.writeText(lastSignature);$('copySignatureBtn').textContent='Copied ✓';setTimeout(()=>$('copySignatureBtn').textContent='Copy signature',1300)}catch{notice('Could not copy the signature automatically.','error')}}
document.querySelectorAll('[data-scenario]').forEach(btn=>{btn.addEventListener('click',()=>{currentKey=btn.dataset.scenario;reset()});btn.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-scenario]')];const i=tabs.indexOf(btn);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=tabs[(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];next.focus();next.click()}})});
$('applyCustomBtn').addEventListener('click',applyCustomScenario);$('executeBtn').addEventListener('click',execute);$('chainPill').addEventListener('click',()=>checkNetwork(true));$('syntheticInfoBtn').addEventListener('click',toggleSyntheticInfo);$('copySignatureBtn').addEventListener('click',copySignature);
document.addEventListener('click',e=>{if(!$('syntheticInfoPanel').hidden&&!$('syntheticInfoBtn').contains(e.target)&&!$('syntheticInfoPanel').contains(e.target)){$('syntheticInfoPanel').hidden=true;$('syntheticInfoBtn').setAttribute('aria-expanded','false')}});
reset();checkNetwork(false);
