(function(global){
  const RPC_URL='https://api.devnet.solana.com';
  const PROOF_LAMPORTS=3_150_000;
  let connection=null,provider=null,recipient=null;
  function web3(){return global.solanaWeb3||global.SolanaWeb3||null}
  function walletProvider(){return global.phantom?.solana||(global.solana?.isPhantom?global.solana:null)||null}
  function ensureClient(){const w3=web3();if(!w3)throw new Error('Solana Web3 client did not load. Check internet access and reload.');if(!connection)connection=new w3.Connection(RPC_URL,'confirmed');if(!recipient)recipient=w3.Keypair.generate();return w3}
  async function checkNetwork(){try{ensureClient();const started=performance.now();const health=await Promise.race([connection.getLatestBlockhash('confirmed'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('RPC timeout')),6500))]);return{ok:!!health?.blockhash,latencyMs:Math.round(performance.now()-started),network:'Solana Devnet'}}catch(error){return{ok:false,error:String(error),network:'Solana Devnet'}}}
  async function connect(){ensureClient();provider=walletProvider();if(!provider)throw new Error('Phantom wallet not detected. Install or enable Phantom and use a development wallet only.');const res=await provider.connect();const pub=res?.publicKey||provider.publicKey;if(!pub)throw new Error('Phantom did not return a wallet address.');const balance=await connection.getBalance(pub,'confirmed');return{wallet:pub.toString(),balanceSol:balance/web3().LAMPORTS_PER_SOL,recipient:recipient.publicKey.toString()}}
  async function getState(){try{ensureClient();provider=walletProvider();if(!provider?.isConnected||!provider.publicKey)return{available:!!provider,connected:false,network:'Solana Devnet'};const balance=await connection.getBalance(provider.publicKey,'confirmed');return{available:true,connected:true,wallet:provider.publicKey.toString(),balanceSol:balance/web3().LAMPORTS_PER_SOL,recipient:recipient.publicKey.toString(),network:'Solana Devnet'}}catch(error){return{available:false,connected:false,error:String(error),network:'Solana Devnet'}}}
  async function fundDevnet(minSol=.02){const w3=ensureClient();if(!provider?.publicKey)await connect();const before=await connection.getBalance(provider.publicKey,'confirmed');if(before>=minSol*w3.LAMPORTS_PER_SOL)return{ok:true,alreadyFunded:true,balanceSol:before/w3.LAMPORTS_PER_SOL};const lamports=Math.ceil(minSol*w3.LAMPORTS_PER_SOL);const signature=await connection.requestAirdrop(provider.publicKey,lamports);let confirmed=false;for(let i=0;i<16;i++){const status=await connection.getSignatureStatuses([signature],{searchTransactionHistory:true});const value=status?.value?.[0];if(value?.err)throw new Error('Devnet airdrop transaction failed.');if(value?.confirmationStatus==='confirmed'||value?.confirmationStatus==='finalized'){confirmed=true;break}await new Promise(r=>setTimeout(r,650))}if(!confirmed)throw new Error('Airdrop was requested but confirmation is taking too long. Retry or use the Devnet faucet.');let after=await connection.getBalance(provider.publicKey,'confirmed');for(let i=0;i<5&&after<=before;i++){await new Promise(r=>setTimeout(r,700));after=await connection.getBalance(provider.publicKey,'confirmed')}if(after<=before)throw new Error('Airdrop was confirmed but the balance has not updated yet. Retry or use the Devnet faucet.');return{ok:true,signature,balanceSol:after/w3.LAMPORTS_PER_SOL,explorer:`https://explorer.solana.com/tx/${signature}?cluster=devnet`}}
  async function execute({amount,onPhase}={}){const w3=ensureClient();if(!provider?.publicKey)await connect();const balance=await connection.getBalance(provider.publicKey,'confirmed');const feeBuffer=5_000_000;if(balance<PROOF_LAMPORTS+feeBuffer)throw new Error('Devnet wallet needs test SOL. Use Fund Devnet first.');onPhase?.('prepare');const tx=new w3.Transaction().add(w3.SystemProgram.transfer({fromPubkey:provider.publicKey,toPubkey:recipient.publicKey,lamports:PROOF_LAMPORTS}));const latest=await connection.getLatestBlockhash('confirmed');tx.recentBlockhash=latest.blockhash;tx.feePayer=provider.publicKey;const totalStart=performance.now();onPhase?.('sign');const signed=await provider.signTransaction(tx);onPhase?.('submit');const sendStart=performance.now();const signature=await connection.sendRawTransaction(signed.serialize(),{skipPreflight:false,maxRetries:3,preflightCommitment:'confirmed'});onPhase?.('confirm');const confirmation=await connection.confirmTransaction({signature,...latest},'confirmed');if(confirmation.value.err)throw new Error('Devnet transaction failed during confirmation.');const confirmedAt=performance.now();const status=await connection.getSignatureStatus(signature,{searchTransactionHistory:true});const txInfo=await connection.getTransaction(signature,{commitment:'confirmed',maxSupportedTransactionVersion:0});const postBalance=await connection.getBalance(provider.publicKey,'confirmed');onPhase?.('complete');return{ok:true,isRealChain:true,network:'SOLANA DEVNET',amount,proofTransferSol:PROOF_LAMPORTS/w3.LAMPORTS_PER_SOL,executionSeconds:(confirmedAt-totalStart)/1000,networkSeconds:(confirmedAt-sendStart)/1000,signature,slot:txInfo?.slot||status?.context?.slot||null,confirmationStatus:status?.value?.confirmationStatus||'confirmed',wallet:provider.publicKey.toString(),recipient:recipient.publicKey.toString(),walletBalanceSol:postBalance/w3.LAMPORTS_PER_SOL,explorer:`https://explorer.solana.com/tx/${signature}?cluster=devnet`,note:'The on-chain transfer is a Devnet execution proof. Scenario LQUSD amounts are synthetic notional.'}}
  global.SolanaAdapter={mode:'REAL_DEVNET_SOL_PROOF',connect,getState,fundDevnet,execute,checkNetwork,proofLamports:PROOF_LAMPORTS};
})(window);
